{% set name = "hfradarpy" %}
{% set version = "0.1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rucool/hfradarpy/archive/{{ version }}.tar.gz
  sha256: ad00e4bc341a17325369c9db50758826d011855d91db3c8f134a4b6b03b62df2

build:
  entry_points:
    - hfradarpy=hfradarpy.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - xarray
    - netcdf4
    - pyproj
    - click
    - dask-core
    - geopandas
    - cartopy
    - matplotlib-base
    - cmocean
    - joblib

test:
  imports:
    - hfradarpy
  commands:
    - pip check
    - hfradarpy --help
  requires:
    - pip

about:
  home: https://github.com/rucool/hfradarpy
  summary: 'Toolbox to read in High Frequency Radar (HFR) files written in the Codar Tabular Format (CTF). Easily read CODAR Ocean Sensors SeaSonde and HELZEL Messtechnik GmbH WERA radial files.'
  license: MIT
  license_file: LICENSE
  doc_url: https://hfradarpy.readthedocs.io/en/latest/
  dev_url: https://github.com/rucool/hfradarpy
  
extra:
  recipe-maintainers:
    - najascutellatus
    - teresaupdyke
